server:
  address: 0.0.0.0
  port: 8080
activemq:
  brokerUrl: ${ACTIVEMQ_BROKER_URL:vm://localhost:61616}
queue:
  name: ${QUEUE_NAME:mainQueue}
worker:
  name: ${HOSTNAME:worker1}
  enabled: ${WORKER_ENABLED:true}
store:
  enabled: ${STORE_ENABLED:true}
spring:
  data:
    mongodb:
      database: testdb
      uri: mongodb://34.89.81.50:27017

