---
apiVersion: v1
kind: Service
metadata:
  name: @branch.name@-backend
spec:
  ports:
  - nodePort: @port.backend@
    port: 8080
    targetPort: 8080
  selector:
    app: backend
  type: LoadBalancer