---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: @branch.name@-backend
spec:
  selector:
    matchLabels:
      app: @branch.name@-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: @branch.name@-backend
        updateTimestamp: "@timestamp@"
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: @branch.name@-backend
        image: jimbono05/spring-boot-k8s-hpa:@project.version@
        imagePullPolicy: Always
        env:
        - name: ACTIVEMQ_BROKER_URL
          value: "tcp://queue:@port.queue@"
        - name: STORE_ENABLED
          value: "false"
        - name: WORKER_ENABLED
          value: "true"
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 256Mi
