---
apiVersion: v1
kind: Service
metadata:
  name: @branch.name@-frontend
spec:
  ports:
  - nodePort: @port.frontend@
    port: 8080
    targetPort: 8080
  selector:
    app: @branch.name@-frontend
  # type: NodePort
  type: LoadBalancer