---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        updateTimestamp: "@timestamp@"
    spec:
      containers:
      - name: frontend
        image: jimbono05/spring-boot-k8s-hpa:@project.version@
        imagePullPolicy: Always
        env:
        - name: ACTIVEMQ_BROKER_URL
          value: "tcp://queue:61616"
        - name: STORE_ENABLED
          value: "true"
        - name: WORKER_ENABLED
          value: "false"
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
