---
apiVersion: v1
kind: Service
metadata:
  name: @branch.name@-frontend
spec:
  ports:
  - nodePort: 32000
    port: 8080
    targetPort: 8080
  selector:
    app: frontend
  # type: NodePort
  type: LoadBalancer