---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: @branch.name@-frontend
spec:
  selector:
    matchLabels:
      app: @branch.name@-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: @branch.name@-frontend
        updateTimestamp: "@timestamp@"
    spec:
      containers:
      - name: @branch.name@-frontend
        image: jimbono05/spring-boot-k8s-hpa:@project.version@-@branch.name@
        imagePullPolicy: Always
        env:
        - name: ACTIVEMQ_BROKER_URL
          value: "tcp://@branch.name@-queue:@port.queue@"
        - name: STORE_ENABLED
          value: "true"
        - name: WORKER_ENABLED
          value: "false"
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
