---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: @branch.name@-queue
spec:
  selector:
    matchLabels:
      app: @branch.name@-queue
  replicas: 1
  template:
    metadata:
      labels:
        app: @branch.name@-queue
        updateTimestamp: "@timestamp@"
    spec:
      containers:
      - name: web
        image: webcenter/activemq:5.14.3
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 61616
        resources:
          limits:
            memory: 512Mi
